sudo: false
arch:
  - amd64
  - ppc64le
language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
  matrix:
    - TEST_SUITE=unit
matrix:
  include:
    - node_js: "6"
      env: TEST_SUITE=lint
before_script:
    - npm run test:prepare
script: npm run-script $TEST_SUITE
